services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=quote_user
      - DATABASE_PASSWORD=1703
      - DATABASE_DBNAME=quotes_db
    networks:
      - quote-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=quote_user
      - POSTGRES_PASSWORD=1703
      - POSTGRES_DB=quotes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - quote-network

volumes:
  postgres_data:

networks:
  quote-network:
    driver: bridge
